services:
  middleware:
    container_name: middleware
    image: rabbitmq:3-management
    depends_on:
      - server
      - client
      - poetry-base

  server:
    container_name: server
    image: tp1-server
    build:
      context: .
      dockerfile: server/Dockerfile
    depends_on:
      - middleware
    volumes:
      - ./lib:/tp1/lib
      - ./middleware:/tp1/middleware
      - ./server:/tp1/server
  
  client:
    container_name: client
    image: tp1-client
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - server
    volumes:
      - ./.data:/tp1/.data
      - ./lib:/tp1/lib
      - ./client:/tp1/client

  worker:
    container_name: worker
    image: tp1-worker
    build:
      context: .
      dockerfile: worker/Dockerfile
    depends_on:
      - middleware
    volumes:
      - ./lib:/tp1/lib
      - ./middleware:/tp1/middleware
      - ./worker:/tp1/worker
