services:
  middleware:
    container_name: middleware
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

  server:
    container_name: server
    image: tp1-server
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - package=server
        - include=middleware
    expose:
      - 9000
    volumes:
      - ../tp1/lib/src:/tp1/lib/src
      - ../tp1/middleware/src:/tp1/middleware/src
      - ../tp1/server/src:/tp1/server/src
  
  client:
    container_name: client
    image: tp1-client
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - package=client
        - include=lib
    depends_on:
      - server
    volumes:
      - ../tp1/.data:/tp1/.data
      - ../tp1/lib/src:/tp1/lib/src
      - ../tp1/client/src:/tp1/client/src

  worker:
    container_name: worker
    image: tp1-worker
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - include=middleware
        - package=worker
    volumes:
      - ../tp1/lib/src:/tp1/lib/src
      - ../tp1/middleware/src:/tp1/middleware/src
      - ../tp1/worker/src:/tp1/worker/src
