[tool.poetry]
name = "middleware"
version = "0.0.1"
description = "Middlewaree para TP1"
authors = ["taielc"]
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = ">=3.10"
common = { path = "../common", develop = true }
pika = "^1.3.2"
